shallow_clone: true

branches:
  except:
    - /^travisci-.*$/
    - /^circleci-.*$/

clone_folder: "c:\\reedsolomon"

environment:
  global:
    STACK_ROOT: "c:\\stack"

cache:
  - C:\stack -> stack.yaml
  # - '%USERPROFILE%\AppData\Local\Programs\stack'

install:
  - curl -ostack.zip -L --insecure http://www.stackage.org/stack/windows-i386
  - 7z x stack.zip stack.exe
  - echo "" | stack setup
  - echo "" | stack exec bash -- -lc "mkdir /tmp; pacman --sync --needed --noconfirm autoconf automake make"
  # Building benchmarks and examples is temporarily disabled due to https://github.com/fpco/stackage/issues/1912
  # - echo "" | stack build --test --bench --only-snapshot --flag=reedsolomon:-LLVM --flag=reedsolomon:examples
  - echo "" | stack build --test --only-snapshot --flag=reedsolomon:-LLVM

build_script:
  - echo "" | stack exec bash -- -lc "cd /c/reedsolomon/cbits; autoreconf -vi"
  # Building benchmarks is temporarily disabled due to https://github.com/fpco/stackage/issues/1912
  # - echo "" | stack build --pedantic --test --no-run-tests --bench --no-run-benchmarks --flag=reedsolomon:-LLVM --flag=reedsolomon:examples
  - echo "" | stack build --pedantic --test --no-run-tests --flag=reedsolomon:-LLVM

test_script:
  - echo "" | stack build --pedantic --test --test-arguments "+RTS -N1" --flag=reedsolomon:-LLVM
  - echo "" | stack build --pedantic --test --test-arguments "--xml junit.xml +RTS -N1" --flag=reedsolomon:-LLVM

on_finish:
  - ps: (new-object net.webclient).UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\junit.xml))
